### ISSUE TITLE
...line 23 in the dockerfile...

### ISSUE THREAD

**Issue by lifeModder19135** [microsoft/vscode-remote-try-python#36]
At line 23 in the dockerfile, there is a line that uses `rm -rf`. THIS IS NOT CONTAINER SAFE ON WINDOWS. Sorry for the caps, but I watched a grown man (for whom I was trying in vein to recover a filesystem) brought to literal tears in front of a stranger on the internet (me) for making this mistake. Sometimes it doesn't recognize the virtual boundary (or else it does, but the `--force` tells it to keep going.) For whatever the reason, It hits the boundary, jumps the fence into the host system, and keeps eating. He said he shut down almost immediately, but it still ate enough disc space that the host was unrecoverable without a reflash of the Windows 10 image.  Just doing my part by letting you know. G'day.

**Comment by Chuxel** [comment]
Given this is in the Docker build rather than in the running container, I'm not sure how it could jump outside of the VM or Docker specific WSL instance it is running. That filesystem doesn't even exist for Windows.  Certainly a `rm -rf` to `/mnt/c` could do that in a WSL instance, but this happens before the container is even created.
